spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://keydeuk-db.c7qcqcww2c6z.ap-northeast-2.rds.amazonaws.com:3306/keyDeuk_shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: admin
        password: quadeight
    jpa:
      hibernate:
          ddl-auto: update