spring:
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB


springdoc:
  version: 2.5.0
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    #display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**