## EC2 server #
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.196.244:3306/keyDeuk?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
  data:
    mongodb:
      uri: mongodb://
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: https://keydeuk-be.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket:
jwt:
  secret:
  grant-type: Bearer
  token-validate-in-seconds: 3600
toss:
  secret-key:

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG